spring:
  application:
    name: demo-service
  datasource:
    url: jdbc:postgresql://postgresql:5432/app
    username: app
    password: changeme
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

server:
  error:
    include-exception: false
    include-message: always
    include-stacktrace: always

security:
  secret: secret12345678
  token-lifetime: 15m
  refresh-token-lifetime: 30d

logstash:
  url: logstash:50000

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include : "info,health,prometheus,metrics"
